# Generated by Django 3.0 on 2021-07-23 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0002_questionnaire_tableofcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='Indirect_cost',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='user',
        ),
        migrations.AddField(
            model_name='tableofcost',
            name='Indirect_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tableofcost',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about.Questionnaire'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Mojibola', max_length=50)),
                ('last_name', models.CharField(default='Ernest', max_length=50)),
                ('phone_number', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('ward_name', models.CharField(max_length=50)),
                ('assent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
                'db_table': 'userprofile',
                'managed': True,
            },
        ),
    ]
