# Generated by Django 3.0 on 2021-07-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20210723_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofcost',
            name='question',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='about.Questionnaire'),
        ),
    ]
