# Generated by Django 3.0 on 2021-07-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_tableofcost_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableofcost',
            name='Qnum',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
