# Generated by Django 3.0 on 2021-07-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_tableofcost_qnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='Qnum',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='tableofcost',
            name='Qnum',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
