# Generated by Django 3.0 on 2021-07-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20210723_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='Cost_of_care_taker',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='How_much',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
