# Generated by Django 3.0 on 2021-07-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210723_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assent_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
